import type { Metadata } from "next";
import { Amarante } from "next/font/google";
import { NavLink, Navbar } from "./home-logic";
import "./globals.css";

const amarante = Amarante({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "The homepage of Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${amarante.className} antialiased`}
      >
        <main>
          <Navbar>
            <NavLink title="Home" location="/" />
            <NavLink title="Notes" location="/notes" />
            <NavLink title="Media" location="/media" />
          </Navbar>
        </main>
        <div className="flex">
          <aside className="w-[15vw]" />
          {children}
          <aside className="w-[15vw]" />
        </div>
      </body>
    </html>
  );
}
