import type { Metadata } from "next";
import { Amarante } from "next/font/google";
import { NavLink, Navbar } from "@/app-content/home";
import "./globals.css";

const amarante = Amarante({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${amarante.className} antialiased`}
      >
        <main>
          <Navbar>
            <NavLink href="\">Home</NavLink>
            <NavLink href="\notes">Notes</NavLink>
            <NavLink href="\stuff">Stuff</NavLink>
            <NavLink href="\movies">Movies</NavLink>
            <NavLink href="\music">Music</NavLink>
          </Navbar>
        </main>
        <div className="flex">
          <aside className="w-[15vw]"/>
          {children}
          <aside className="w-[15vw]"/>
        </div>
      </body>
    </html>
  );
}
